In [20]:
# AI Study Assistant

## Module 3 : Data Preprocessing

### Objectives

#- Load datasets
#- Understand data
#- Check missing values
#- Check duplicates
#- Clean dataset
#- Save cleaned dataset

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os

print("Libraries Imported Successfully")

Libraries Imported Successfully

In [4]:
print(os.getcwd())

C:\Users\ABC\Desktop\DATASET\notebooks

In [5]:
ap_df = pd.read_csv("../dataset/processed/antennas_and_propagation_dataset.csv")

es_df = pd.read_csv("../dataset/processed/embedded_systems_dataset.csv")

print("Datasets Loaded Successfully")

Datasets Loaded Successfully

In [6]:
ap_df.head()

,Question,Subject,Chapter,Years_Appeared,Frequency,Average_Marks,Difficulty,Priority
0,"Define the antenna term in different ways, and...",Antennas and Propagation,1. Basic antenna concepts,"Summer 2023, Winter 2024",2,3.0,Easy,High
1,Draw and explain different parts of radiation ...,Antennas and Propagation,1. Basic antenna concepts,"Summer 2023, Winter 2024",2,3.0,Easy,High
2,List down different types of antennas and expl...,Antennas and Propagation,1. Basic antenna concepts,"Winter 2022, Summer 2025, Winter 2025",3,5.0,Easy,Medium
3,Explain different types of antenna apertures.,Antennas and Propagation,1. Basic antenna concepts,Summer 2024,1,3.0,Easy,Low
4,Obtain the ratio of E_theta and H_phi field co...,Antennas and Propagation,2. Radiation of Electric dipole,"Winter 2021, Summer 2022, Winter 2022, Winter ...",5,6.4,Hard,High

In [7]:
es_df.head()

,Question,Subject,Chapter,Years_Appeared,Frequency,Average_Marks,Difficulty,Priority
0,"Define and classify Embedded Systems, and list...",Embedded Systems,1. Introduction to Embedded Systems,"Summer 2022, Winter 2022, Winter 2023, Summer ...",6,3.33,Easy,High
1,Describe the components of an Embedded System.,Embedded Systems,1. Introduction to Embedded Systems,Winter 2024,1,4.00,Easy,Low
2,Describe the skills required for an embedded s...,Embedded Systems,1. Introduction to Embedded Systems,"Winter 2021, Summer 2022, Summer 2023, Summer ...",4,4.25,Easy,High
3,"Describe an embedded processor as GPP, ASIP an...",Embedded Systems,1. Introduction to Embedded Systems,"Winter 2021, Summer 2023",2,5.50,Medium,Medium
4,List down the components available on SoC and ...,Embedded Systems,1. Introduction to Embedded Systems,Winter 2021,1,7.00,Medium,Low

In [8]:
print("Antennas Dataset Shape :", ap_df.shape)

print("Embedded Dataset Shape :", es_df.shape)

Antennas Dataset Shape : (64, 8)
Embedded Dataset Shape : (90, 8)

In [9]:
ap_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64 entries, 0 to 63
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Question        64 non-null     object
 1   Subject         64 non-null     object
 2   Chapter         64 non-null     object
 3   Years_Appeared  64 non-null     object
 4   Frequency       64 non-null     int64
 5   Average_Marks   64 non-null     float64
 6   Difficulty      64 non-null     object
 7   Priority        64 non-null     object
dtypes: float64(1), int64(1), object(6)
memory usage: 4.1+ KB

In [10]:
es_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 90 entries, 0 to 89
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Question        90 non-null     object
 1   Subject         90 non-null     object
 2   Chapter         90 non-null     object
 3   Years_Appeared  90 non-null     object
 4   Frequency       90 non-null     int64
 5   Average_Marks   90 non-null     float64
 6   Difficulty      90 non-null     object
 7   Priority        90 non-null     object
dtypes: float64(1), int64(1), object(6)
memory usage: 5.8+ KB

In [11]:
ap_df.describe(include="all")

,Question,Subject,Chapter,Years_Appeared,Frequency,Average_Marks,Difficulty,Priority
count,64,64,64,64,64.00000,64.000000,64,64
unique,64,1,15,41,NaN,NaN,3,3
top,"Define the antenna term in different ways, and...",Antennas and Propagation,3. Antenna parameters and definitions,Winter 2023,NaN,NaN,Medium,High
freq,1,64,13,7,NaN,NaN,37,32
mean,NaN,NaN,NaN,NaN,3.37500,4.643594,NaN,NaN
std,NaN,NaN,NaN,NaN,3.02109,1.432370,NaN,NaN
min,NaN,NaN,NaN,NaN,1.00000,3.000000,NaN,NaN
25%,NaN,NaN,NaN,NaN,1.00000,3.400000,NaN,NaN
50%,NaN,NaN,NaN,NaN,2.00000,4.110000,NaN,NaN
75%,NaN,NaN,NaN,NaN,5.00000,5.575000,NaN,NaN
max,NaN,NaN,NaN,NaN,12.00000,7.000000,NaN,NaN

In [12]:
es_df.describe(include="all")

,Question,Subject,Chapter,Years_Appeared,Frequency,Average_Marks,Difficulty,Priority
count,90,90,90,90,90.000000,90.000000,90,90
unique,90,1,7,48,NaN,NaN,3,3
top,"Define and classify Embedded Systems, and list...",Embedded Systems,7. MSP430 (Case Study),Winter 2025,NaN,NaN,Medium,Low
freq,1,90,21,9,NaN,NaN,61,43
mean,NaN,NaN,NaN,NaN,2.488889,4.870667,NaN,NaN
std,NaN,NaN,NaN,NaN,1.990113,1.599010,NaN,NaN
min,NaN,NaN,NaN,NaN,1.000000,3.000000,NaN,NaN
25%,NaN,NaN,NaN,NaN,1.000000,3.347500,NaN,NaN
50%,NaN,NaN,NaN,NaN,2.000000,4.225000,NaN,NaN
75%,NaN,NaN,NaN,NaN,3.000000,7.000000,NaN,NaN
max,NaN,NaN,NaN,NaN,9.000000,7.000000,NaN,NaN

In [13]:
print(ap_df.isnull().sum())

Question          0
Subject           0
Chapter           0
Years_Appeared    0
Frequency         0
Average_Marks     0
Difficulty        0
Priority          0
dtype: int64

In [14]:
print(es_df.isnull().sum())

Question          0
Subject           0
Chapter           0
Years_Appeared    0
Frequency         0
Average_Marks     0
Difficulty        0
Priority          0
dtype: int64

In [15]:
print("AP Duplicate :", ap_df.duplicated().sum())

print("Embedded Duplicate :", es_df.duplicated().sum())

AP Duplicate : 0
Embedded Duplicate : 0

In [16]:
ap_df = ap_df.drop_duplicates()

es_df = es_df.drop_duplicates()

print("Duplicate Removed Successfully")

Duplicate Removed Successfully

In [17]:
ap_df.to_csv(
    "../dataset/processed/clean_antennas_dataset.csv",
    index=False
)

es_df.to_csv(
    "../dataset/processed/clean_embedded_dataset.csv",
    index=False
)

print("Clean Dataset Saved Successfully")

Clean Dataset Saved Successfully